-- ===============================
-- CLIENTES
-- ===============================
INSERT INTO client (external_id, school_name, cafeteria_name, location, student_count) VALUES
('EXT001','Gluck Haus Cafe Marista Paranaense','CANTINA VLUPT','Curitiba PR',2609),
('EXT002','Cantina Santa Maria Marista','CANTINA VLUPT','Curitiba PR',2428),
('EXT003','Pôla Lanches Positivo Júnior','CANTINA VLUPT','Curitiba PR',1557),
('EXT004','Pôla Lanches Positivo Ângelo Sampaio','CANTINA VLUPT','Curitiba PR',908),
('EXT005','Gluck Haus Colégio Bom Jesus Centro','CANTINA VLUPT','Curitiba PR',1387),
('EXT006','Cantina Bon Bini Colégio Marista Anjo da Guarda','CANTINA VLUPT','Curitiba PR',1123),
('EXT007','Cardapium Bom Jesus Divina Providência','CANTINA VLUPT','Curitiba PR',812),
('EXT008','Cantina Arte & Sabor Colégio Adventista Alto Boqueirão','CANTINA VLUPT','Curitiba PR',1250),
('EXT009','Cantina Sesi Boqueirão','CANTINA VLUPT','Curitiba PR',0),
('EXT010','Cantina da Nona Escola Bambinata','CANTINA VLUPT','Curitiba PR',600),
('EXT011','Oliveiras Foods Colégio Vicentino São José','CANTINA VLUPT','Curitiba PR',613),
('EXT012','Graces Coffee Escola Grace','CANTINA VLUPT','Curitiba PR',620),
('EXT013','Cantinho do Sabor Curso e Colégio Acesso - Boqueirão','CANTINA VLUPT','Curitiba PR',545),
('EXT014','Eskillus Escola Interativa - Bacacheri','CANTINA VLUPT','Curitiba PR',354),
('EXT015','Red House Red House - Campus I','CANTINA VLUPT','Curitiba PR',200),
('EXT016','Cantina Solos Escola Solos','CANTINA VLUPT','Curitiba PR',330),
('EXT017','Coração da Nonna Santa Teresinha Escola Santa Teresinha do Menino Jesus','CANTINA VLUPT','Curitiba PR',130),
('EXT018','Cantina Escolar Cavalcanti Colégio Amplação','CANTINA VLUPT','Curitiba PR',926),
('EXT019','Maaloe Red House - Campus 2','CANTINA VLUPT','Curitiba PR',200),
('EXT020','La Merienda Gastronomia Colegio Assunção','CANTINA VLUPT','Curitiba PR',1000),
('EXT021','Taki Taki Esic Business & Marketing School -faculdade E Colégio Internacional','CANTINA VLUPT','Curitiba PR',700),
('EXT022','Cantina Lumen Escola Lumen Ltda','CANTINA VLUPT','Curitiba PR',241),
('EXT023','Cantina Cosmos Escola Cosmos','CANTINA VLUPT','Curitiba PR',158),
('EXT024','Cantina Escola Sao Carlos Borromeo','CANTINA VLUPT','Curitiba PR',450),
('EXT025','Cantina Sabor & Arte Colégio Horizonte','CANTINA VLUPT','Curitiba PR',780),
('EXT026','Cantina Bom Paladar Colégio Estrela','CANTINA VLUPT','Curitiba PR',920),
('EXT027','Cantina Delícias do Saber Escola Aurora','CANTINA VLUPT','Curitiba PR',300),
('EXT028','Cantina Pão Quente Escola Pioneira','CANTINA VLUPT','Curitiba PR',1100),
('EXT029','Cantina Vida & Sabor Instituto Progresso','CANTINA VLUPT','Curitiba PR',640),
('EXT030','Cantina NutriMais Colégio Integração','CANTINA VLUPT','Curitiba PR',850),
('EXT031','Cantina Terra Café Centro Educacional Vale Verde','CANTINA VLUPT','Curitiba PR',430),
('EXT032','Cantina Gourmet Kids Colégio Alfa','CANTINA VLUPT','Curitiba PR',720),
('EXT033','Cantina Bom Gosto Escola Prisma','CANTINA VLUPT','Curitiba PR',380),
('EXT034','Cantina Saborosa Escola Vitória','CANTINA VLUPT','Curitiba PR',510),
('EXT035','Cantina MixKids Ensino Brilhante','CANTINA VLUPT','Curitiba PR',610),
('EXT036','Cantina Trigo & Mel Escola Horizonte Azul','CANTINA VLUPT','Curitiba PR',200),
('EXT037','Cantina NutriSaber Colégio Avante','CANTINA VLUPT','Curitiba PR',1000),
('EXT038','Cantina Casa do Pão Escola Nacional','CANTINA VLUPT','Curitiba PR',310),
('EXT039','Cantina Tropical Escola Brasil Futuro','CANTINA VLUPT','Curitiba PR',900),
('EXT040','Cantina Mil Sabores Escola Criativa','CANTINA VLUPT','Curitiba PR',550),
('EXT041','Cantina Planet Café Colégio Alpha Plus','CANTINA VLUPT','Curitiba PR',410),
('EXT042','Cantina Estudante Feliz Escola Conquista','CANTINA VLUPT','Curitiba PR',820),
('EXT043','Cantina Bom Sabor Kids Escola Premium','CANTINA VLUPT','Curitiba PR',760),
('EXT044','Cantina Viva Escola Evolução','CANTINA VLUPT','Curitiba PR',640),
('EXT045','Cantina Sabores do Sol Colégio Diamante','CANTINA VLUPT','Curitiba PR',450),
('EXT046','Cantina NutriVida Escola Horizonte Novo','CANTINA VLUPT','Curitiba PR',280),
('EXT047','Cantina TikTak Kids Colégio Vitória Plus','CANTINA VLUPT','Curitiba PR',1250),
('EXT048','Cantina Delícia Urbana Colégio Expressão','CANTINA VLUPT','Curitiba PR',540),
('EXT049','Cantina Nova Era Escola Caminhos','CANTINA VLUPT','Curitiba PR',600),
('EXT050','Cantina SuperKids Colégio Aprende+','CANTINA VLUPT','Curitiba PR',720),
('EXT051','Cantina Central Kids Colégio Ideal','CANTINA VLUPT','Curitiba PR',310),
('EXT052','Cantina BigCoffee Escola Alpha Kids','CANTINA VLUPT','Curitiba PR',400),
('EXT053','Cantina Estação Sabor Colégio Mater Dei','CANTINA VLUPT','Curitiba PR',900),
('EXT054','Cantina Chef Kids Escola Progresso Júnior','CANTINA EXTRA','Belo Horizonte MG',780),
('EXT055','Cantina Alegria Escola Horizonte Kids','CANTINA EXTRA','Belo Horizonte MG',330),
('EXT056','Cantina Doce Sabor Colégio Majestade','CANTINA EXTRA','Belo Horizonte MG',510),
('EXT057','Cantina Sabor Real Escola UniKids','CANTINA Franchising','São Paulo SP',440),
('EXT058','Cantina Kids & Café Escola Master','CANTINA Franchising','São Paulo SP',810),
('EXT059','Cantina Mundo Verde Escola Alfa Júnior','CANTINA Franchising','São Paulo SP',290),
('EXT060','Cantina MaxKids Colégio Vitória Infantil','CANTINA Franchising','São Paulo SP',500);

-- ===============================
-- CLIENT_DATA
-- ===============================
INSERT INTO client_data
(client_id, month_date, cantina_percent, registered_students,
 average_cantina_per_student, average_pedagogical_per_student,
 order_count, revenue, profitability, revenue_loss,
 orders_outside_vpt, average_ticket_app, notes)
VALUES
(1, '2025-01-01', 0.2540, 320, 48.50, 22.30, 120, 15400.50, 18.20, 450.00, 15, 12.80, 'Janeiro estável'),
(1, '2025-02-01', 0.2680, 340, 50.10, 23.10, 132, 16820.75, 19.40, 380.00, 12, 13.40, 'Crescimento pós férias'),

(2, '2025-01-01', 0.2310, 290, 44.20, 20.80, 110, 13950.00, 16.90, 520.00, 18, 11.90, 'Leve queda'),
(3, '2025-01-01', 0.3010, 410, 55.00, 26.00, 180, 22540.00, 21.30, 300.00, 9, 15.20, 'Excelente performance');
